services:
  ctportal:
    container_name: ctportal
    image: nguyentrantrung/ctportal:latest
    ports:
      - 6145:3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    networks:
      - server
networks:
  server:
    external: true
